"""add_price_observation_index

Revision ID: 78e51101aa0f
Revises: a254453635dc
Create Date: 2026-09-30 04:26:55.575831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e51101aa0f'
down_revision: Union[str, Sequence[str], None] = 'a254453635dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_price_observations_product_id_observed_at', 'price_observations', ['product_id', 'observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_observations_product_id_observed_at', table_name='price_observations')
    # ### end Alembic commands ###
